### ISSUE TITLE
Journal Text entry

### ISSUE THREAD

**Issue by lewis-mclan** [Firm-Collective/ai-journal#1]
**As a user of the One Accord app, I want to be able to enter text entries into a private journal, so I can also keep my private thoughts and prayer impressions in the same app.**

Background:
The One Accord app makes it possible for people around the world to pray, share communion and many more things with each other in synergy and also share their prayer impressions and spiritual insights in a common live stream. In addition to this the next step is the development of a personal journal.

In a first step, this journal is just for the individual person itself (this epic).

In a second step we will add the possibility to also share it with others. (another epic).

**Acceptance criteria (can be individual user stories that can build on the basic feature):**

- [ ] simple pure Text entries are okay in the first instance
- [ ] add simple RTF elements as bold, italic, underline and clickable links to the entries
- [ ] The journal should keep my entries with the time of entry and be ordered from newest (top) to oldest
- [ ] Unsent journal entries should be saved as draft automatically
- [ ] ability to add tags manually to later find my entries
- [ ] full text search
- [ ] ability to filter for date and tags
- [ ] capability to upload photos as well

**Steps needed (some can be done in parallel):**
1. Break down the epic into smaller work packages and vertical stories
2. Iterate on a design and screens for this part of the journal (work with firm.collective closely for feedback)
3. test a micro service architecture to build it on
4. start simple and iterate, building on very basic features and design
