### ISSUE TITLE
Record Voice Memos

### ISSUE THREAD

**Issue by lewis-mclan** [Firm-Collective/ai-journal#2]
**As a user, I would like to be able to record voice memos within the app and add them just like text based entries, I can use speech or audio as another medium that I'm already used to using frequently just as much as text.**

Acceptance criteria (can be their own user stories to break it down in small pieces):

- [ ] I can record, pause and save with (or without) title right in the app
- [ ] the recording shows up inline with my journal timeline with the date recorded
- [ ] I can add meta tags and they are automatically suggested on saving on the same saving screen as the optional title
- [ ] I have the option of deleting my entry
- [ ] I can filter my Journal to just show voice memos or text entries
